### add company
POST localhost:8080/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzIwMjUxNTM4LCJleHAiOjE3MjAyNTUxMzh9.6nR29tocjgJKWrV1TJ0Zr048W9S219MLbVdw5u8tThFr5iR5Mt0Ih52SfIjCKOv9pVjD541uUsCQ5mYvSLlqHw

{
  "ticker": "O"
}

### add company
POST localhost:8080/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzIwMjcxNzA0LCJleHAiOjE3MjAyNzUzMDR9.TifhuSWLS88kUobSlz_72TtlGbgewaabiGAvUKjXSatZ82bMhZI2CNAQabmd8JBKBf40bnxESuUTEmlDwajJtg

{
  "ticker": "MMM"
}

### add company
POST localhost:8080/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzIwMjUxNTM4LCJleHAiOjE3MjAyNTUxMzh9.6nR29tocjgJKWrV1TJ0Zr048W9S219MLbVdw5u8tThFr5iR5Mt0Ih52SfIjCKOv9pVjD541uUsCQ5mYvSLlqHw

{
"ticker": "COKE"
}

### get company list
GET localhost:8080/company
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzIwMjUxNTM4LCJleHAiOjE3MjAyNTUxMzh9.6nR29tocjgJKWrV1TJ0Zr048W9S219MLbVdw5u8tThFr5iR5Mt0Ih52SfIjCKOv9pVjD541uUsCQ5mYvSLlqHw

### search company by keyword
GET localhost:8080/company/autocomplete?keyword=R
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzIwMjUxNTM4LCJleHAiOjE3MjAyNTUxMzh9.6nR29tocjgJKWrV1TJ0Zr048W9S219MLbVdw5u8tThFr5iR5Mt0Ih52SfIjCKOv9pVjD541uUsCQ5mYvSLlqHw

### delete company by company ticker
DELETE localhost:8080/company/MMM
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzIwMjUxNTM4LCJleHAiOjE3MjAyNTUxMzh9.6nR29tocjgJKWrV1TJ0Zr048W9S219MLbVdw5u8tThFr5iR5Mt0Ih52SfIjCKOv9pVjD541uUsCQ5mYvSLlqHw