### get company and dividend info
GET localhost:8080/finance/dividend/3M Company
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJncmFjZSIsInJvbGVzIjpbIlJPTEVfUkVBRCIsIlJPTEVfV1JJVEUiXSwiaWF0IjoxNzIwMjcxNzA0LCJleHAiOjE3MjAyNzUzMDR9.TifhuSWLS88kUobSlz_72TtlGbgewaabiGAvUKjXSatZ82bMhZI2CNAQabmd8JBKBf40bnxESuUTEmlDwajJtg